---
- name: Create file {{ hosts_file }}
  become: true
  become_user: root
  template:
    src: "{{ hosts_template }}"
    dest: "{{ hosts_file }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: yes
