---
- name: Configure Timezone
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  vars:
    timezone_value: "Europe/Berlin"
  tasks:
  - name: Set timezone to {{ timezone_value }}
    timezone:
      name: "{{ timezone_value }}"

  - name: Copy over the TIMESYNCD configuration
    template: src=../timesyncd.conf dest=/etc/systemd/timesyncd.conf
    notify:
      - restart systemd-timesyncd.service
    tags: timesync

  handlers:
    - name: restart systemd-timesyncd.service
      service: name=systemd-timesyncd.service state=restarted
...
